# Generated by Django 5.1.5 on 2025-02-01 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.TextField(default='Not specified', help_text='What could be improved?'),
        ),
        migrations.AddField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, help_text='Link to the business website', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.TextField(default='Not specified', help_text='What did you love about this business?'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default='', help_text='Your detailed review'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Review', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1'), django.core.validators.MaxValueValidator(10, message='Rating cannot be higher than 10')]),
        ),
    ]
