# Generated by Django 5.1.5 on 2025-02-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_remove_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(help_text='What could be improved?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, default='link', help_text='Link to the business website', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.TextField(help_text='What did you love about this business?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(help_text='Your detailed review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
